# Generated by Django 4.1.4 on 2022-12-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название блюда')),
                ('price', models.IntegerField(verbose_name='Цена блюда')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('compound', models.CharField(max_length=300, verbose_name='Состав')),
                ('category', models.CharField(choices=[('Холодные роллы', 'Холодные роллы'), ('Напитки', 'Напитки'), ('Горячие роллы', 'Горячие роллы'), ('Запеченные роллы', 'Запеченные роллы'), ('Десерты', 'Десерты'), ('Горячие блюда', 'Горячие блюда'), ('Салаты', 'Салаты'), ('Супы', 'Супы')], max_length=100, verbose_name='Категория')),
            ],
        ),
    ]
